export const COUNT_INCREMENT = 'INCREMENT'
export const COUNT_DECREMENT = 'DECREMENT'


export const AUTH_POPUP = 'AUTH_POPUP'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR'